version: 2.1

orbs: 
  docker: circleci/docker@2.0.1
  ggshield: gitguardian/ggshield@1.1.0

workflows:
  build-docker-image-only:
    jobs:
      - ggshield/scan:
          name: Scan using Gitguardian shield
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
          context:
            - gitguardian

      - docker/publish:
          name: Build and Publish to Docker Hub
          image: thinxcloud/worker
          context:
            - dockerhub