version: 2.1

orbs:
  docker: circleci/docker@2.8.0
  ggshield: gitguardian/ggshield@1.1.4
  node: circleci/node@1.1.6
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:

  test:
    docker:
      - image: thinxcloud/console-build-env:latest
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Run Tests
                no_output_timeout: 1m
                command: |
                  npm install

workflows:

  build-and-publish:
    jobs:
      - test:
          context:
            - coveralls-worker
            - rollbar
            - sonarcloud

      - docker/publish:
          name: build and publish
          image: thinxcloud/worker
          tag: latest
          context:
            - dockerhub
            - rollbar
          requires:
            - test
