version: 2.1

orbs: 
  docker: circleci/docker@2.0.1
  ggshield: gitguardian/ggshield@1.1.0

context:
  - dockerhub
  - gitguardian

workflows:
  build-docker-image-only:
    jobs:
      - gg-shield/scan:
          name: Scan using Gitguardian Shield
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>

      - docker/publish:
          name: Build and Publish to Docker Hub
          image: thinxcloud/worker